[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "aarch64-linux-gnu-gcc"

[target.mips-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "gcc-mips-linux-gnu"

[target.mipsel-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "gcc-mipsel-linux-gnu"

[target.mips64-unknown-linux-gnuabi64]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "gcc-mips64-linux-gnuabi64"

[target.mips64el-unknown-linux-gnuabi64]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "gcc-mips64el-linux-gnuabi64"

[target.riscv64gc-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "gcc-riscv64-linux-gnu"
